---
- name: updating repo
  yum:
    name: "*"
    state: latest

- name: install openjdk 11
  yum:
    name: "{{java_package}}"
    state: present

- name: Downloading tomcat file
  get_url:
     url: "{{tomcat_url}}"
     dest: /usr/local/

- name: Extracting downlaod tomcat
  unarchive:
     src: "/usr/local/apache-tomcat-{{tomcat_version}}.tar.gz"
     dest: /usr/local/
     remote_src: yes


- name: Replacing default port with required port
  template:
     src: /var/lib/jenkins/workspace/Ansible-Jenkins/roles/tomcat/templates/server.xml.j2
     dest: /usr/local/apache-tomcat-{{tomcat_version}}/conf/server.xml
     become: true


- name: Changing manager_users
  template:
     src: /var/lib/jenkins/workspace/Ansible-Jenkins/roles/tomcat/templates/manager-context.xml.j2
     dest: /usr/local/apache-tomcat-{{tomcat_version}}/webapps/manager/META-INF/context.xml
     become: true

- name: Changing Hostmanager_users
  template:
     src: /var/lib/jenkins/workspace/Ansible-Jenkins/roles/tomcat/templates/manager-context.xml.j2
     dest:  /usr/local/apache-tomcat-{{tomcat_version}}/webapps/host-manager/META-INF/context.xml
     become: true


- name: tomcat-user
  template:
     src: /var/lib/jenkins/workspace/Ansible-Jenkins/roles/tomcat/templates/tomcat-users.xml.j2
     dest:  /usr/local/apache-tomcat-{{tomcat_version}}/conf/tomcat-users.xml
     become: true


- name: Deploy war file to tomcat server
  copy:
    src: /var/lib/jenkins/workspace/Ansible-Jenkins/target/LoginWebApp-2.war
    dest: /usr/local/apache-tomcat-{{tomcat_version}}/webapps
  notify:
     - restart the tomcat server
