---
  - name: install_configure_tomcat
    hosts: tomcat
    gather_facts: false
    vars:
      req_java: java-1.8.0-openjdk
      tomcat_port: 8010
    become: yes
    become_user: root
    tasks:
      - name: updating repo
        yum:
          name: "*"
          state: latest

      - name: installing required java
        yum:
          name: "{{req_java}}"
          state: present

      - name: Downloading tomcat file
        get_url:
          url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.85/bin/apache-tomcat-8.5.85.tar.gz
          dest: /usr/local/

      - name: Extracting downlaod tomcat
        unarchive:
          src: "/usr/local/apache-tomcat-8.5.85.tar.gz"
          dest: /usr/local/
          remote_src: yes
          
      - name: start tomcat 
        service:
          name: tomcat
          state: started
          become: true


      
      - name: Deploy war file to tomcat server
        copy:
         src: /var/lib/jenkins/workspace/Ansible-Jenkins/target/LoginWebApp-2.war
         dest: /usr/local/apache-tomcat-8.5.85/webapps
         
      - name: Replacing default port with required port
        template:
           src: /var/lib/jenkins/workspace/Ansible-Jenkins/roles/tomcat/templates/server.xml.j2
           dest: /usr/local/apache-tomcat-8.5.85/conf/server.xml
        become: true
        
        notify: 
         - restarted tomcat
      
      - name: Changing manager_users
        template:
           src: /var/lib/jenkins/workspace/Ansible-Jenkins/roles/tomcat/templates/manager-context.xml.j2
           dest: /usr/local/apache-tomcat-8.5.85/webapps/manager/META-INF/context.xml
        become: true
        
        notify: 
         - restarted tomcat


      - name: Changing Hostmanager_users
        template:
           src: /var/lib/jenkins/workspace/Ansible-Jenkins/roles/tomcat/templates/manager-context.xml.j2
           dest:  /usr/local/apache-tomcat-8.5.85/webapps/host-manager/META-INF/context.xml
        become: true
        
        notify: 
         - restarted tomcat

      - name: tomcat-user
        template:
           src: /var/lib/jenkins/workspace/Ansible-Jenkins/roles/tomcat/templates/tomcat-users.xml.j2
           dest:  /usr/local/apache-tomcat-8.5.85/conf/tomcat-users.xml
        become: true
        
        notify: 
         - restarted tomcat
        
    handlers:
      - name: restarted tomcat
        service:
          name: tomcat
          state: restarted

   
          


      
